/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedWordsIndexRouteImport } from './routes/_authenticated/words/index'
import { Route as AuthenticatedWordsNewRouteImport } from './routes/_authenticated/words/new'
import { Route as AuthenticatedWordsWordIdEditRouteImport } from './routes/_authenticated/words/$wordId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWordsIndexRoute = AuthenticatedWordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWordsNewRoute = AuthenticatedWordsNewRouteImport.update({
  id: '/words/new',
  path: '/words/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWordsWordIdEditRoute =
  AuthenticatedWordsWordIdEditRouteImport.update({
    id: '/words/$wordId/edit',
    path: '/words/$wordId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/words/new': typeof AuthenticatedWordsNewRoute
  '/words/': typeof AuthenticatedWordsIndexRoute
  '/words/$wordId/edit': typeof AuthenticatedWordsWordIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/words/new': typeof AuthenticatedWordsNewRoute
  '/words': typeof AuthenticatedWordsIndexRoute
  '/words/$wordId/edit': typeof AuthenticatedWordsWordIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/words/new': typeof AuthenticatedWordsNewRoute
  '/_authenticated/words/': typeof AuthenticatedWordsIndexRoute
  '/_authenticated/words/$wordId/edit': typeof AuthenticatedWordsWordIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/words/new' | '/words/' | '/words/$wordId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/words/new' | '/words' | '/words/$wordId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/words/new'
    | '/_authenticated/words/'
    | '/_authenticated/words/$wordId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/words/': {
      id: '/_authenticated/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof AuthenticatedWordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/words/new': {
      id: '/_authenticated/words/new'
      path: '/words/new'
      fullPath: '/words/new'
      preLoaderRoute: typeof AuthenticatedWordsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/words/$wordId/edit': {
      id: '/_authenticated/words/$wordId/edit'
      path: '/words/$wordId/edit'
      fullPath: '/words/$wordId/edit'
      preLoaderRoute: typeof AuthenticatedWordsWordIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWordsNewRoute: typeof AuthenticatedWordsNewRoute
  AuthenticatedWordsIndexRoute: typeof AuthenticatedWordsIndexRoute
  AuthenticatedWordsWordIdEditRoute: typeof AuthenticatedWordsWordIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWordsNewRoute: AuthenticatedWordsNewRoute,
  AuthenticatedWordsIndexRoute: AuthenticatedWordsIndexRoute,
  AuthenticatedWordsWordIdEditRoute: AuthenticatedWordsWordIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
